apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam:::role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::012112873555:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2A7PRJ7U3LIW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::012112873555:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-24T21:04:48Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-24T21:04:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-02-24T21:11:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2845"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a4b43848-804f-4d66-96af-a38b64f579d4
