apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::012112873555:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1D93AI2TC3D7Q
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-24T21:04:48Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-24T21:04:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1528"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a4b43848-804f-4d66-96af-a38b64f579d4
