apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::012112873555:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4YULUB9C6VSC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::012112873555:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-25T10:52:42Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-25T10:52:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1536"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c0561384-78e6-4aa4-9853-ca0fa1da826b
